import { Header } from "./header/Header";
import { Banner } from "./home/Banner"; 
import { Services } from "./home/Services";
import { MobileApp } from "./home/MobileApp";
import { Benefits } from "./home/Benefits";
import { Network } from "./home/Network";
import { Doctors } from "./home/Doctors";
import { Feedbacks } from "./home/Feedbacks";
import { News } from "./home/News";
import { Footer } from "./footer/Footer";
export { Header, Banner, Services, MobileApp, Benefits, Network, Doctors, Feedbacks, News, Footer };